CREATE TABLE IF NOT EXISTS sites (
    id SERIAL PRIMARY KEY NOT NULL,
    site VARCHAR(2000) NOT NULL UNIQUE,
    login VARCHAR(2000) NOT NULL UNIQUE,
    password VARCHAR(2000),
    registration BOOLEAN
);